version: "3.9"
services:
  auth:
    build: ./back/Auth
    ports:
      - "5002:5000"
    env_file: ./back/Auth/.env

  frontend:
    build: ./front
    ports:
      - "5173:80"
    depends_on:
      - auth
    env_file: ./front/.env
